import { Category, Listing, Room } from "@/lib/types";

export const categories: Category[] = [
  { id: "all", label: "All" },
  { id: "city", label: "City" },
  { id: "beach", label: "Beach" },
  { id: "mountain", label: "Mountain" },
  { id: "design", label: "Design" },
  { id: "family", label: "Family" },
];

export const listings: Listing[] = [
  {
    id: "madrid-central-suite",
    title: "Central Suite in Madrid",
    location: "Madrid, Spain",
    dates: "Jun 10 - Jun 14",
    host: "Hosted by Alba",
    category: "city",
    pricePerNight: 122,
    rating: 4.91,
    reviews: 128,
    imageUrl: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Modern apartment living room with natural light",
    galleryImages: [
      "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    badge: "Guest favorite",
    tone: "from-amber-200 via-orange-100 to-rose-200",
  },
  {
    id: "granada-patio-home",
    title: "Patio Home in Granada",
    location: "Granada, Spain",
    dates: "Jul 03 - Jul 07",
    host: "Hosted by Mario",
    category: "design",
    pricePerNight: 98,
    rating: 4.83,
    reviews: 84,
    imageUrl: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Cozy patio home with warm decor",
    galleryImages: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    tone: "from-stone-200 via-amber-100 to-yellow-100",
  },
  {
    id: "malaga-breeze-flat",
    title: "Breeze Flat in Malaga",
    location: "Malaga, Spain",
    dates: "Aug 12 - Aug 16",
    host: "Hosted by Lucia",
    category: "beach",
    pricePerNight: 140,
    rating: 4.95,
    reviews: 211,
    imageUrl: "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Bright coastal apartment near the sea",
    galleryImages: [
      "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    badge: "Super host",
    tone: "from-sky-200 via-cyan-100 to-blue-100",
  },
  {
    id: "sevilla-terrace-loft",
    title: "Terrace Loft in Sevilla",
    location: "Sevilla, Spain",
    dates: "Sep 01 - Sep 05",
    host: "Hosted by Irene",
    category: "city",
    pricePerNight: 115,
    rating: 4.79,
    reviews: 66,
    imageUrl: "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Loft with terrace and city view",
    galleryImages: [
      "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/3935336/pexels-photo-3935336.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    tone: "from-rose-200 via-pink-100 to-orange-100",
  },
  {
    id: "asturias-green-cabin",
    title: "Green Cabin in Asturias",
    location: "Asturias, Spain",
    dates: "Jul 18 - Jul 22",
    host: "Hosted by Daniel",
    category: "mountain",
    pricePerNight: 89,
    rating: 4.88,
    reviews: 102,
    imageUrl: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Cabin retreat surrounded by green mountains",
    galleryImages: [
      "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    tone: "from-emerald-200 via-lime-100 to-green-100",
  },
  {
    id: "valencia-family-loft",
    title: "Family Loft in Valencia",
    location: "Valencia, Spain",
    dates: "Aug 22 - Aug 28",
    host: "Hosted by Paula",
    category: "family",
    pricePerNight: 156,
    rating: 4.86,
    reviews: 149,
    imageUrl: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Spacious family loft with dining area",
    galleryImages: [
      "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    badge: "Great for groups",
    tone: "from-indigo-200 via-violet-100 to-fuchsia-100",
  },
  {
    id: "cadiz-sunset-studio",
    title: "Sunset Studio in Cadiz",
    location: "Cadiz, Spain",
    dates: "Jun 20 - Jun 23",
    host: "Hosted by Juan",
    category: "beach",
    pricePerNight: 101,
    rating: 4.74,
    reviews: 54,
    imageUrl: "https://images.pexels.com/photos/2029734/pexels-photo-2029734.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Sunny studio near the beach at sunset",
    galleryImages: [
      "https://images.pexels.com/photos/2029734/pexels-photo-2029734.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    tone: "from-orange-200 via-amber-100 to-yellow-100",
  },
  {
    id: "bilbao-riverside-apartment",
    title: "Riverside Apartment in Bilbao",
    location: "Bilbao, Spain",
    dates: "Sep 15 - Sep 19",
    host: "Hosted by Laura",
    category: "city",
    pricePerNight: 133,
    rating: 4.9,
    reviews: 93,
    imageUrl: "https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg?auto=compress&cs=tinysrgb&w=1200",
    imageAlt: "Riverside apartment with modern interior",
    galleryImages: [
      "https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1400",
      "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1400",
    ],
    tone: "from-slate-200 via-zinc-100 to-stone-100",
  },
];

const defaultAmenities = [
  "Kitchen",
  "Wifi",
  "Dedicated workspace",
  "TV",
  "Air conditioning",
  "Washer",
  "Self check-in",
  "Free parking",
];

const defaultDescription =
  "Warm and comfortable home close to local spots. The space has natural light, practical amenities, and easy access to transport and food. Ideal for short or medium stays.";

export const rooms: Room[] = listings.map((listing) => ({
  id: listing.id,
  title: listing.title,
  location: listing.location,
  dates: listing.dates,
  rating: listing.rating,
  reviews: listing.reviews,
  pricePerNight: listing.pricePerNight,
  description: defaultDescription,
  host: {
    name: listing.host.replace("Hosted by ", ""),
    yearsHosting: 2 + (listing.id.length % 6),
    avatarTone: listing.tone,
  },
  images: listing.galleryImages,
  amenities: defaultAmenities,
}));

export function getRoomById(id: string): Room | undefined {
  return rooms.find((room) => room.id === id);
}
